.github/release-drafter.yml, .github/workflows/fill-gh-draft-release.yml
⚠️ release-drafter cannot be tested through the PR, because the config file must be present in the default branch.
It will be tested using the [github-actions-playground repository](https://github.com/process-analytics/github-actions-playground)
See https://github.com/process-analytics/github-actions-playground/pull/29
closes #29
=> [INFRA] Setup release-drafter for release notes inialization

README.md
=> [DOC] Explain where the BPMN diagram examples come from

inst/htmlwidgets/bpmnVisualization.js
Previously, this generated an error preventing adding the rest of the overlays present in the array.
Fixes #44
=> [FIX] Manage adding overlays referencing an unknown bpmn element

.github/workflows/R-CMD-check.yaml, DESCRIPTION, man/bpmnVisualization-package.Rd
Clean the package Rmd file
The GitHub worklow runs more R version (release and devel)
covers #10
=> [INFRA] Clean warnings to facilitate CRAN submission 

README.md
Format the code to avoid displaying scrollbars (at least on GitHub)
=> [DOC] Improve examples rendering in the README

.github/release-drafter.yml, CONTRIBUTING.md
When we close issues as part of the release, we now include them in dedicated milestones.
So, update the release notes template and the release procedure to not forget milestone management.
=> [DOC] Include milestone management in release

.github/release-drafter.yml, .github/workflows/fill-gh-draft-release.yml
`release-drafter` configuration
- 'Dependencies' category: collapsed if more than 5 elements
- exclude `dependabot` from the CONTRIBUTORS list. We removed it manually on every release so make it automatically
- generate a link to the full changelog in the git history.
GitHub workflow
- use a specific action version to better control updates and the use of new features. `dependabot` will create PR for action updates when new release-drafter releases are available
- allow running release-drafter on demand. This is useful to fix the release notes after PR relabel
**Notes**
Replicate what we did in https://github.com/process-analytics/bpmn-visualization-js/pull/1759, https://github.com/process-analytics/bpmn-visualization-js/pull/1851 and …
=> [INFRA] Improve the release-notes generation

inst/examples/Email_Voting.bpmn
Some terminal waypoints were defined inside the shapes. `bpmn-visualization@0.23.0` doesn't fix the rendering anymore: it is not putting them on the shape perimeter.
So fix the coordinates to make them appear on the perimeters.
This has been detected in https://github.com/process-analytics/bpmn-visualization-R/pull/65#pullrequestreview-924731140
before | now
------ | --------
=> [EXAMPLE] Improve waypoints in the 'email voting' diagram

.github/release-drafter.yml
The link was directing to the bpmn-visualization JS/TS lib
=> [INFRA] Fix the milestone link in the release-drafter configuration

.github/workflows/update_bpmn_visualization_version.yml
The default branch of the repository is not `master` but `main`. So fix the `peter-evans/create-pull-request` actions inputs accordingly.
=> [INFRA] Fix branch name in workflow updating bpmn-visualization

DESCRIPTION, man/bpmnVisualization-package.Rd
The following updates are based on the last CRAN submission feedback:
- DESCRIPTION: explain acronyms
- bpmnVisualization-package.Rd
- replace `\dontrun` with `\donttest`
- update the example
covers #10 
> Please always explain all acronyms in the description text. -> 'BPMN'
> 
> \dontrun{} should only be used if the example really cannot be executed (e.g. because of missing additional software, missing API keys, ...) by the user. That's why wrapping examples in \dontrun{} adds the comment ("# Not run:") as a warning for the user. Does not seem necessary. Please replace \dontrun with \donttest. -> bpmnVisualization-package.Rd
> 
> Please unwrap the examples if they are executable in < 5 sec, or replace dontrun{} with \donttest{}.
> 
> Please fix and resubmit.
=> [DOC] Fix the documentation to better match CRAN requirements

MAINTAINERS.md
Add a notice about `bpmn-visualization` TypeScript library bump
=> [DOC] Improve the "Release Notes" writing steps

.github/workflows/release.yml, DESCRIPTION, MAINTAINERS.md
Add new workflow for the release: `release.yml` including the following steps (in order):
- unprotect the branch
- generate the new version with https://github.com/marketplace/actions/create-new-semantic-version (based on the latest git tag)
- update the README.md and DESCRIPTION files with the new version
- commit the changes
- tag, then push the commit and tag
- update the DESCRIPTION file with the new development version
- commit and push it
- protect the branch again
Closes #47 
See this PR to see the tests with `patch`, `minor` and `major` version: https://github.com/process-analytics/github-actions-playground/pull/173
=> [INFRA] Automate tag and files update

MAINTAINERS.md
Note: improvements based on feedback collected during the v0.2.2 release.
- remove reference to a closed issue that is completed
- manual release: add the "git tag" step
- CRAN submission: better explain how to fill out the form
=> [DOC] Improve the release process steps

.github/actions/build-documentation-site/action.yml, .github/workflows/publish-documentation-pr-preview.yml, .github/workflows/publish-documentation.yml, DESCRIPTION
Use a GitHub workflow to deploy
Update the DESCRIPTION file to mention the `gh-pages` URL
Update the Release workflow: update the release version in the doc site as well (index.md)
closes  #19
=> [DOC] Deploy Documentation to GitHub Pages

MAINTAINERS.md
Update the maintainers documentation to remind writers to notify users through the release notes. In this case, the new version of the package will be install using GitHub.
closes #159
=> [DOC] Warn users for releases not available on CRAN

.github/workflows/R-CMD-check.yaml
Some configuration changes were forgotten in the workflow at the time of the name change (from `bpmnVisualization` to `bpmnVisualizationR`).
=> [INFRA] Fix the package renaming in the R-CMD-check workflow

.Rbuildignore, .github/workflows/release.yml, DESCRIPTION, MAINTAINERS.md, cran-comments.md, inst/WORDLIST, man/bpmnVisualizationR-package.Rd, tests/spelling.R
Fix the last submission: https://github.com/process-analytics/bpmn-visualization-R/issues/10#issuecomment-1376718157
Status ok : https://builder.r-hub.io/status/bpmnVisualizationR_0.3.0.9000.tar.gz-a9d46a21e09ee0ab9e90fc169cf6f824
Changes:
* Corrected the URLs and removed `LazyData` field in the DESCRIPTION file.
* Added a new file `WORDLIST` to allow custom words with `spelling` package.
* Updated the documentation of the maintainers to execute `rhub` package before starting a new release
* Added a new file `cran-comments.md` for the CRAN submission
* Updated the `release` workflow to update the last version in `cran-comments.md`
=> [DOC] Fix CRAN submission

DESCRIPTION, R/bpmnVisualizationR.R, R/funs.R, cran-comments.md, man/bpmnVisualizationR-package.Rd, man/bpmnVisualizationR-shiny-output.Rd, man/bpmnVisualizationR-shiny-render.Rd, man/create_overlay.Rd, man/display.Rd
Fix the CRAN submission, according the last rejection:
> If there are references describing the methods in your package, please
> add these in the description field of your DESCRIPTION file in the form
> authors (year) <doi:...>
> authors (year) <arXiv:...>
> authors (year, ISBN:...)
> or if those are not available: <https:...>
> with no space after 'doi:', 'arXiv:', 'https:' and angle brackets for
> auto-linking. (If you want to add a title as well please put it in
> quotes: "Title")
> 
> Please always write package names, software names and API (application
> programming interface) names in single quotes in title and description.
> e.g: --> 'TypeScript'
> Please note that package names are case sensitive.
> 
> Please fix and resubmit.
covers #10
=> fix: update the DESCRIPTION file and the R doc according last submission

.github/dependabot.yml, .github/workflows/pr-metadata-checks.yml, .github/workflows/release.yml, .github/workflows/update-bpmn-visualization-version.yml, MAINTAINERS.md
Related changes:
- Add a dedicated workflow to enforce the rule. It runs on `pull_request_target` to handle PR created by Dependabot and from fork repositories.
- Dependabot configuration: change PR title prefix.
- Update the GitHub workflows that create commits and PR. They now follow "conventional commits".
- Update the release process documentation.
closes #202
For tests, see https://github.com/process-analytics/github-actions-playground/issues/213
=> chore: ensure that the PR title follows "Conventional Commits"

README.md, index.md
- add badges in the `README.md` and `index.md` for **CRAN** publication
- update _how to install_ from **CRAN** in the `README.md` and `index.md`
- update comments
Covers #10
=> docs: update the documentation after CRAN publication

R/bpmnVisualizationR.R, man/display.Rd
Highlight the default positions and styles in a dedicated example.
=> docs: add more examples for styles and positions of overlays

MAINTAINERS.md
The first thing to decide prior starting the release is to know if we publish on CRAN.
Based on feedback collected during the 0.4.0 release.
=> docs: improve the release process

DESCRIPTION, R/bpmnVisualizationR.R, R/funs.R, man/bpmnVisualizationR-shiny-output.Rd, man/bpmnVisualizationR-shiny-render.Rd, man/create_overlay.Rd, man/create_overlay_style.Rd, man/display.Rd, man/overlay_edge_position.Rd, man/overlay_shape_position.Rd
To simplify the writing and the reading of the documentation of #13, I enabled the markdown support.  
https://cran.r-project.org/web/packages/roxygen2/vignettes/rd-formatting.html
=> docs: enabling markdown support

inst/htmlwidgets/bpmnVisualizationR.js
Call the new `BpmnElementsRegistry.getModelElementsByIds` method introduced in bpmn-visualization@0.39.0.
- Detected in https://github.com/process-analytics/bpmn-visualization-R/pull/247/files/be77a8dc61ae0152401d90d82a6043907e2af925#r1324022400
- The surge preview can be used to validate the changes: the documentation of the `display` R function call the JavaScript code that manages overlays.
- Introduction of the new method: https://github.com/process-analytics/bpmn-visualization-js/releases/tag/v0.39.0
=> refactor: simplify overlay management in JS bridge code

.github/workflows/release.yml
The workflow commits to the main branch and the branch protection configured in the GitHub repository prevents this for all users.
Previously, the protection was temporarily bypassed and the user performing the commit required administrator permissions (due to the configuration of the branch protection).
Now protection is done using GitHub branch ruleset, and there's no need to bypass protection. In this way, workflow can be simplified.
The settings have already been updated
- ruleset replaces branch protection: https://github.com/process-analytics/bpmn-visualization-R/rules (publicly visible)
repository
- permissions of the user performing the Git operations in the repository has been downgraded. ⚠️ **IMPORTANT**: this PR must then be merged prior doing the next release. The workflow …
=> ci(release): eliminate bypassing of branch protection
